// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using World.Data;

namespace World.Migrations
{
    [DbContext(typeof(WorldContext))]
    [Migration("20210425174001_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("World.Data.Models.PathModel", b =>
                {
                    b.Property<uint>("PathID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<uint>("WorldID")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ZoneID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PathID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Paths");
                });

            modelBuilder.Entity("World.Data.Models.PathTileModel", b =>
                {
                    b.Property<uint>("TileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PathID")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TileX")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TileY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("TileID");

                    b.HasIndex("PathID");

                    b.ToTable("PathTiles");
                });

            modelBuilder.Entity("World.Data.Models.PlayerModel", b =>
                {
                    b.Property<long>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("World.Data.Models.PathModel", b =>
                {
                    b.HasOne("World.Data.Models.PlayerModel", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("World.Data.Models.PathTileModel", b =>
                {
                    b.HasOne("World.Data.Models.PathModel", "Path")
                        .WithMany("Tiles")
                        .HasForeignKey("PathID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Path");
                });

            modelBuilder.Entity("World.Data.Models.PathModel", b =>
                {
                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
